### ISSUE TITLE
nginx verto endpoint obsolete?

### ISSUE THREAD

**Issue by erisd** [bigbluebutton/bigbluebutton#10908]
Hey,

i found a broken nginx endpoint in the bbb config which seems to be not in use:
location /verto {
  proxy_pass https://127.0.0.1:8082;

First i fixed it, but after looking where its used (because we don't have problems regarding that) I found that its deleted in 2019:
https://github.com/bigbluebutton/bigbluebutton/commit/8380875e70dcf35b7193a3c8519d5a34c676917b

So, if I'm right, please remove:
- /etc/bigbluebutton/nginx/verto.nginx
- /opt/freeswitch/etc/freeswitch/autoload_configs/verto.conf.xml
- akka-bbb-fsesl/fs_conf_files/conf/autoload_configs/verto.conf.xml

Thanks!

**Comment by prlanzarin** [comment]
@erisd Hey,

Partially correct.
- `/etc/bigbluebutton/nginx/verto.nginx`: obsolete (cc @ffdixon reckon we could remove this from packaging in 2.3)
- `/opt/freeswitch/etc/freeswitch/autoload_configs/verto.conf.xml`: isn't obsolete per se. Comes with FreeSWITCH vanilla conf. No action needed.
- `akka-bbb-fsesl/fs_conf_files/conf/autoload_configs/verto.conf.xml`: obsolete. We can remove it from the codebase in 2.3 (cc @antobinary).

Background of those files: early HTML5 client builds where screensharing worked through FreeSWITCH's mod_verto+mod_conference. Leftover files.

**Comment by ffdixon** [comment]
> /etc/bigbluebutton/nginx/verto.nginx: obsolete (cc @ffdixon reckon we could remove this from packaging in 2.3)

Done.

> /opt/freeswitch/etc/freeswitch/autoload_configs/verto.conf.xml: isn't obsolete per se. Comes with FreeSWITCH vanilla conf. No action needed.

It belongs to `bbb-apps-screenshare`, which is related to the older Flash-based code and will not be installed by default in 2.3.

> akka-bbb-fsesl/fs_conf_files/conf/autoload_configs/verto.conf.xml: obsolete. We can remove it from the codebase in 2.3 (cc @antobinary).

Hmm ... could not find this package on 2.2 or 2.3.

**Comment by erisd** [comment]
> @erisd Hey,
> 
> Background of those files: early HTML5 client builds where screensharing worked through FreeSWITCH's mod_verto+mod_conference. Leftover files.

Thanks! Can you also disable these Modules? I also see an Freeswitch mongo Plugin which is configured but not in use, and a unconfigured pgsql Plugin....
(This should reduce the startup time and the warnings...)

**Comment by znerol** [comment]
There is tons of FreeSWITCH config which is not used by BigBlueButton. FreeSWITCH ships with the [vanilla](https://github.com/signalwire/freeswitch/tree/master/conf/vanilla) config which demonstrates all the bells and whistles. Regrettably it is quite common that people start their projects with that config (maybe for historical reasons). However, there is also a [minimal](https://github.com/signalwire/freeswitch/tree/master/conf/minimal) config which is more appropriate for bootstrapping production systems.

I'm operating BBB with an [adapted minimal configuration](https://github.com/znerol/bbb-minimal-fs). No support for recording however (not required in my case).

**Comment by ffdixon** [comment]
It's a good suggestion -- we're using the vanilla FreeSWITCH configuration files with some modifications, but we could pare them down as part of the future work on packaging.

**Comment by antobinary** [comment]
Update
Looks like ... `freeswitch/conf/autoload_configs/verto.conf.xml` was removed in https://github.com/bigbluebutton/bigbluebutton/pull/11864

`akka-bbb-fsesl/fs_conf_files/conf/autoload_configs/verto.conf.xml` is still present

**Comment by znerol** [comment]
I did not know about `akka-bbb-fsesl/fs_conf_files`. Looking at the contents I'm pretty sure they can be removed as well.

**Comment by prlanzarin** [comment]
That whole directory should be removed, correct.

As I mentioned previously: that whole thing was added when screen share ran through Verto (1.1, 2.0). It doesn't anymore, sot there's no use for it. But I believe packaging has to be adjusted beforehand if it's still fetching stuff from there to avoid any kind of breakage.

**Comment by antobinary** [comment]
Packaging (2.3+ at least) is not fetching anything from `fs_conf_files`

**Comment by antobinary** [comment]
All three files are now removed (as of 2.3-beta4). Thanks all! Closing.
