### ISSUE TITLE
presentation screen is distorted when survey is resized

### ISSUE THREAD

**Issue by burakguder** [bigbluebutton/bigbluebutton#11946]
When I test the beta version I get the following error.

sizing in the survey area disrupts the presentation screen

2.3-beta-2
https://test23.bigbluebutton.org/

OS : Linux Mint
Browser : Chrome Version 88.0.4324.150 (Official Build) (64-bit)

Presentation screen sizing does not work properly when the survey area is sized with the mouse

![bbb-error](https://user-images.githubusercontent.com/560147/114035899-378e9f00-9888-11eb-8e07-36c4b1e83da0.gif)

**Comment by hiroshisuga** [comment]
Related to #11924. Hopefully fixed by #11900 and #11925.

**Comment by antobinary** [comment]
Likely resolved in #11925 which will ship with BBB 2.3-beta3

**Comment by hiroshisuga** [comment]
It seems to me that #11925 has been already merged to 2.3beta3. And if the current test23 server is run by 2.3beta3 (it seems so because the quick polling triggers the layout rearrangement), this issue has not been solved yet. #11962 could provide a solution (not sure if is the best one).

**Comment by daminebenq** [comment]
Hi, I couldn't reproduce this. I believe that this is not anymore reproducible.

**Comment by hiroshisuga** [comment]
Ok. I will close my PR.

**Comment by PhMemmel** [comment]
I doublechecked, #11925 is included in 2.3-beta-3. However, I can still reproduce this behavior on test23.bigbluebutton.org, currently running bbb-html5 1588 which is 2.3-beta-3. So this doesn't seem to be resolved.

**Comment by hiroshisuga** [comment]
Hi @PhMemmel ,
Could you kindly check if #11962 can fix the problem? I have confirmed that 11962 fixes it (whereas #11925 not) on 2.3beta1 but not on the latest one.

**Comment by PhMemmel** [comment]
In my dev environment on latest develop branch your PR #11962 fixes the problem, yes. I did the comparison directly without and with your PR change. Could reproduce it without your PR and couldn't reproduce it anymore with it.

I would suggest to include this PR as long as there isn't a better fix for this (as you mentioned).

**Comment by hiroshisuga** [comment]
Thanks @PhMemmel , that is exactly what I have seen in my local environment. I will reopen #11962 as a draft and let the other people decide.
