### ISSUE TITLE
[2.6] Whiteboard on iPad in fullscreen

### ISSUE THREAD

**Issue by SamuelWei** [bigbluebutton/bigbluebutton#17722]
**Describe the bug**
To use the maximum space on an ipad, users wan't to use it in fullscreen
However, the pointer is always shown in the top-left, while using the pencil and the cursor tool

**To Reproduce**
1. Open whiteboard in fullscreen
2. Select cursor tool
3. Move cursor with apple pencil
4. See pointer not moving in the top-left

**Expected behavior**
Show current cursor/pen position
Allow users with pencils to use pencil to show something on the slide, without selecting

**Actual behavior**
Pointer is always shown in the top-left
With a pencil you cannot only point at something, you always select elements on the slide

**Screenshots**
![Bildschirmfoto 2023-04-25 um 19 12 25](https://user-images.githubusercontent.com/4281791/234352434-6c64ca9f-b987-43f4-96d7-2ddd7129f9b8.jpeg)

**BBB version:**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Client build: 574
BigBlueButton version: 2.6.5
Server: test26.bigbluebutton.org

**Desktop (please complete the following information):**
 - OS: ipadOS 16.2
-  Browser Safari

**Comment by antobinary** [comment]
Thanks for reporting!

**Comment by antobinary** [comment]
@KDSBrowne are we able to do this on our 3.0 whiteboard?

**Comment by KDSBrowne** [comment]
I was not able to reproduce this. Tested with an older ipad (OS 15.6.1)

**Comment by SamuelWei** [comment]
Reopend, Issue still exists in the iPad App (at least on demo.bigbluebutton.org)

**Comment by ramonlsouza** [comment]
Hello @SamuelWei / @KDSBrowne - has the issue been resolved by #20748?

**Comment by samuelwei** [comment]
The App doesn't work at all with the latest 3.0 release on demo.bigbluebutton.org.
It is stuck at a blue screen. Maybe related to https://github.com/bigbluebutton/bigbluebutton-tablet/issues/58

![image](https://github.com/user-attachments/assets/f800004c-7295-48f4-b472-772bf86ab874)

**Comment by SamuelWei** [comment]
Maybe related to #https://github.com/bigbluebutton/bigbluebutton-tablet/issues/58

**Comment by samuelwei** [comment]
On BBB 2.7.16

The pointer is still shown at the wrong position in fullscreen.

https://github.com/user-attachments/assets/993cf993-55ac-465f-8456-8d0501e0d975
