### ISSUE TITLE
Incorrect size of annotations in recordings

### ISSUE THREAD

**Issue by vasylOstrovskyi** [bigbluebutton/bigbluebutton#17958]
**Describe the bug**
During playback, annotations of slides are smaller than were during presentation.

**To Reproduce**
1. Start session, start recording.
2. Draw something on the whiteboard, e.g., rectangle
3. Stop recording, stop session.
4. Play recording. The annotations are smaller than expected.

**Screenshots**
If applicable, add screenshots to help explain your
![Знімок екрана з 2023-05-21 15-41-41](https://github.com/bigbluebutton/bigbluebutton/assets/33595182/b5760b24-1891-4d0e-b17c-29a93e3ae132)
![Знімок екрана з 2023-05-21 15-43-24](https://github.com/bigbluebutton/bigbluebutton/assets/33595182/1bbb88b7-6114-4e74-8a66-ffb9024522da)
 problem.

**BBB server**
2.6.7

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome

**Comment by ffdixon** [comment]
Thanks for pointing this out.

**Comment by kepstin** [comment]
This was fixed in BigBlueButton 2.6.1 (bbb-playback 5.0.0). Do you have any out of date packages on your BigBlueButtons erver?

**Comment by vasylOstrovskyi** [comment]
To be sure, I removed all bbb* and related packages, completely removed /usr/local/bigbluebutton and /var/bigbluebutton directories, removed all docker images on my test server, then reinstalled bbb by the standard script. 
Now I have (version 2.6.7 (1206))
```
root@bbb2:/usr/share/bigbluebutton# dpkg -l |grep bbb-playback
ii  bbb-playback                               1:2.6-15                          amd64        BigBlueButton playback
ii  bbb-playback-presentation                  1:2.6-13                          amd64        BigBluebutton playback of presentation
```
The reported issue is still there. Missed something?

**Comment by vasylOstrovskyi** [comment]
Well, I found `/etc/bigbluebutton/recording/recording.yml` where the first line was `bbb_version: '2.6.0'`. After changing it to `bbb_version: '2.6.1'`, the issue disappeared.
Thanks!
 Vasyl.

**Comment by kepstin** [comment]
The configuration in `/etc/bigbluebutton/recording/recording.yml` is merged with the configuration provided by BigBlueButton. You should only set configuration in the file in `/etc` which has changed on your system and needs to be overridden.
