### ISSUE TITLE
Some images are not shown in presentation if using Firefox as client and using a PDF created by MS Office

### ISSUE THREAD

**Issue by wolbernd** [bigbluebutton/bigbluebutton#17969]
**Describe the bug**
When uploading and showing a presentation that has been created by MS Powerpoint (Version 2016 tested) and been exported from Powerpoint as a PDF using the MS Office export feature some of the images are not shown in the frontend when using Firefox as a client.

If the presentation area is resized (e.g. by changing the browser window size or by removing the public chat tab) the missing images are shown. This resizing needs to be done on all frontends. If the presenter resizes the browser window they will see the missing images. This does not propagate to other participants.

**To Reproduce**

1. Create a Powerpoint Presentation containing several images on one page (I have created a test presentation [test.pptx](https://github.com/bigbluebutton/bigbluebutton/files/11540293/test.pptx) )
2. Export as a PDF file (Example: [test.pdf](https://github.com/bigbluebutton/bigbluebutton/files/11540313/test.pdf) )
3. Open Firefox as a maximized Window and start a BBB meeting
4. Wait until the default presentation has been processed and upload the pdf file

**Expected behavior**
See all images in the presentation area (In the supplied example it should be 4 photographs):

**Actual behavior**
In some cases only see two or three images: ![Screenshot_20230523_082642](https://github.com/bigbluebutton/bigbluebutton/assets/24311754/713f8cb6-1e44-4d58-8f5c-3902f3529a81)

PDF file opened in pdf viewer:
![Screenshot_20230523_084117](https://github.com/bigbluebutton/bigbluebutton/assets/24311754/56cefa66-d959-4a7e-80fe-fa0335dc7748)

**BBB version:**
BigBlueButton Server 2.6.7 (1221)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 113.0

Also tested with Firefox 102.11esr on Windows

**Additional context**
Honestly I'm not entirely sure that this is the right place to file this bug for a fix. It could also be a problem in how MS creates PDF files or some bug in Firefox.

**Comment by ffdixon** [comment]
I was able to reproduce this on FireFox on Mac OS X using FireFox 113.0.1 

https://github.com/bigbluebutton/bigbluebutton/assets/290351/ae589c8b-22e8-42f2-8720-341eb3940a1f

**Comment by ffdixon** [comment]
Thanks again for the test.pdf.  In uploading this on BigBlueButton 2.5.17 all images are visible when expanding/collapsing the chat.

Same file on 2.6.7, one of the images disappears when expanding/collapsing the chat.

https://github.com/bigbluebutton/bigbluebutton/assets/290351/cb995227-8f82-4bec-a314-6612a7caa654

**Comment by ramonlsouza** [comment]
looks like if a slide with images takes longer to load, tldraw will not try to render it again - [Adding .1px](https://github.com/bigbluebutton/bigbluebutton/pull/17983/files#diff-c3d2592d10171afb0e63117f0c6bfe25e5a3848c629f4e9aba60dddb68ff7671R244) (no impact in image size, but still triggers a new render) after the image is ready should fix it

**Comment by einhirn** [comment]
This still happens in 2.6.8 and it seems to be the same issue as in #16826 .  Looking at it more closely, we found out that it always seems to be the last image that's missing and that any slight change (e.g. Presenter moving Pointer, s/o typing in chat, new user entering the room, window resize etc.) makes the missing picture appear...

**Comment by mconstabel** [comment]
Still happens in 2.6.10 and FF 115.0. If the otp (130 slides) is loaded  and I switch forward trough the slides sometimes 1 or more images are not shown. If the presentator move the cursor a litte up 1px into the slide (or switch forward/backward or backward/forward), the images are shown for all clients.
(If a client click or move the cursor on the slide, the image is also shown for him. )
After then i can move backward and forward, the images keeps visible. Until forward to some other slide... Where sometimes 1/1, 1/3, 2/3 or all images are not shown.
The otp is big. if I split it in 30 slides, then it works better, nearly never missing images. If I export it as PDF and upload the 30 slides pdf, the missing images are more often.
If the presentator use chrome(ium), always all images are visible for him.

If one dev need our otp, I can send it as pm, its not public.

The otp was created with MS Office 2013, imported in Libreoffice 7.4, saved as otp.

Regards,
Mike
