### ISSUE TITLE
[Cluster Proxy] - CORS error when using different domains for bbb-cluster-proxy and bbb-host(s)

### ISSUE THREAD

**Issue by gschwienbacher** [bigbluebutton/bigbluebutton#23637]
CORS error when using different domains for bbb-cluster-proxy and bbb-host(s).

**To Reproduce**
Use different domain for bbb-proxy and bbb-host when installing / configuring bbb-cluster-proxy setup, see: https://docs.bigbluebutton.org/administration/cluster-proxy/

**Expected behavior**
Different domains should be possible - otherwise add it to the documentation. A start meeting request ends with "Oops, something went wrong..." 

**Actual behavior**
Different domains break the bbb-cluster-proxy setup.

Error message:

==> /var/log/bigbluebutton/bbb-web.log <==
2025-07-29T08:23:51.388+02:00 DEBUG o.b.w.c.ConnectionController - Error while authenticating graphql connection {whjrjz9y2z1sinm5}: Invalid sessionToken

==> /var/log/syslog <==
Jul 29 08:23:51 tm-bbb03 java[6288]: 2025-07-29T08:23:51.388+02:00 DEBUG o.b.w.c.ConnectionController - Error while authenticating graphql connection {whjrjz9y2z1sinm5}: Invalid sessionToken

Browser Console:
html5client/:1 Access to fetch at 'https://bbb-01.domain1.com/api/rest/clientSettings' from origin 'https://bbb.domain2.com' has been blocked by CORS policy:

=> domain1 is the domain where the bbb server "resides"
=> domain2 is the domain where the cluster proxy server "resides"

If additional information is necessary, please let me know.

**Comment by gustavotrott** [comment]
I had to set `allowRequestsWithoutSession=true` in `/etc/bigbluebutton/bbb-web.properties` to get it working.
Still trying to find a way to resolve the issue without relying on this setting.


_I think the cookies are being set for the proxy domain, so when a request is made to the BBB domain, the cookie isn’t included (preventing session validation). Fixing this will probably require some core changes._

**Comment by gustavotrott** [comment]
Hey @gschwienbacher,
are both domains subdomains of the same main domain?
For example:
`domain1 = bbb.mydomain.com`
`domain2 = proxy.mydomain.com`

If that's the case, the best approach is to configure BBB to set cookies for the root domain (`mydomain.com`).
You can do that with the following command:

```bash
sudo yq eval '.server.servlet.session.cookie.domain = "mydomain.com"' -i /usr/share/bbb-web/WEB-INF/classes/application.yml
```

Then restart the API:

```bash
sudo systemctl restart bbb-web
```

That should solve the issue.

**Comment by gustavotrott** [comment]
A better alternative that should work for any domain, change this part of the Docs:

Proxy Cluster Server:
```nginx
location /bbb-01/html5client/ {
  proxy_pass https://bbb-01.example.com/bbb-01/html5client/;
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "Upgrade";
}

location /bbb-01/bigbluebutton/api {
  proxy_pass https://bbb-01.example.com/bigbluebutton/api;
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "Upgrade";
}
```

replace with this:

```nginx
location /bbb-01/html5client/ {
  proxy_pass https://bbb-01.example.com/bbb-01/html5client/;
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "Upgrade";
}

location /bbb-01/ {
  proxy_pass https://bbb-01.example.com/;
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "Upgrade";
}

location = /bbb-01/bigbluebutton/api/join {
  return 301 https://bbb-01.example.com/bigbluebutton/api/join?$args;
}
```

This way the cookie will be created at the domain `bbb-01.example.com` and all requests to this domain will be able to authenticate.

**Comment by gschwienbacher** [comment]
> Hey [@gschwienbacher](https://github.com/gschwienbacher), are both domains subdomains of the same main domain? For example: `domain1 = bbb.mydomain.com` `domain2 = proxy.mydomain.com`
> 
> If that's the case, the best approach is to configure BBB to set cookies for the root domain (`mydomain.com`). You can do that with the following command:
> 
> sudo yq eval '.server.servlet.session.cookie.domain = "mydomain.com"' -i /usr/share/bbb-web/WEB-INF/classes/application.yml
> Then restart the API:
> 
> sudo systemctl restart bbb-web
> That should solve the issue.

Hey @gustavotrott  - thanks for your reply. Unfortunately they are not subdomains of the same main domain.
it's really bbb.domain1.com (cluster proxy) and bbb-03.domain2.com (bbb-server)

So we'll have to go / try out your 2nd alternative. In the meantime we switched the domain name of the bbb-server to the domain1.com Domain to avoid the issue. So I don't know when we are going to be able to test this (if you'd expect us to do so?)

**Comment by michelleDeko** [comment]
Hi @gustavotrott - me and @gschwienbacher now tested your second option with the following nginx config:
```
    location /mii/html5client/ {
        proxy_pass https://bbb-mii.domain2.net/mii/html5client/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /mii/ {
      proxy_pass https://bbb-mii.domain2.net/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
    }
    
    location = /mii/bigbluebutton/api/join {
      return 301 https://bbb-mii.domain2.net/bigbluebutton/api/join?$args;
    }
```

We are now using "domain1.com" for the proxy and "domain2.net" for the BBB. 
We are still getting the same error:
`Aug 08 08:41:25 bbb-mii java[69224]: 2025-08-08T08:41:25.725+02:00 DEBUG o.b.w.c.ConnectionController - Error while authenticating graphql connection {6bjsnaooi6ocxrib}: Invalid sessionToken`

**Comment by gustavotrott** [comment]
hey @michelleDeko , thanks for testing it!

Just to confirm, did you restart Nginx after applying the new config?
I ask because I had the exact same error before adding this proxy configuration, and restarting resolved it.

Also, when using API-Mate (`bbb-conf --salt`) with `redirect=false`, the join request should be redirected to the `bbb-mii.domain2.net` domain. Could you double-check that as well?

https://github.com/user-attachments/assets/30770b6a-7aff-4ee1-84d7-6e78a53071f9

**Comment by michelleDeko** [comment]
Hi, yes I did restart the nginx and when trying it with API Mate, I still get the same error. Also, in your video, you're still using the same domain, instead of a different one, which is why it works for you. (you use ***subdomain***.bbb.imdt.dev for both things

We are testing it with 2 different domains, meaning:
bbb-proxy.**domain1.com** -> bbb-01.**domain2.net**

**Comment by gustavotrott** [comment]
I use the same root domain but the cookie is being set only for the subdomain:

<img width="3116" height="1959" alt="Image" src="https://github.com/user-attachments/assets/b756c1ed-f797-4900-90c8-baa83c78baa3" />

**Comment by gustavotrott** [comment]
In short, the specific error `Error while authenticating graphql connection {whjrjz9y2z1sinm5}: Invalid sessionToken` is likely caused by the cookie being set for `proxy.domain1.com`.

Since the `/join` request is made through `proxy.domain1.com`, the session cookie ends up being scoped to that domain. However, the GraphqL authentication request goes to `bbb-mii.domain2.net`, which doesn’t have access to the cookie, hence the authentication fails.

To fix this, I changed the `/join` request to use `bbb-mii.domain2.net`, so the cookie gets set for the correct domain, allowing Graphql to authenticate properly.

---

Regarding the CORS error:

`Access to fetch at 'https://bbb-01.domain1.com/api/rest/clientSettings' from origin 'https://bbb.domain2.com/' has been blocked by CORS policy`

I didn't encounter this issue, it should be resolved by the configurations added to `/etc/bigbluebutton/bbb-graphql-middleware.yml` and `/etc/bigbluebutton/bbb-graphql-server.env`.

**Comment by michelleDeko** [comment]
> I use the same root domain but the cookie is being set only for the subdomain:
> 
> <img width="3116" height="1959" alt="Image" src="https://github.com/user-attachments/assets/b756c1ed-f797-4900-90c8-baa83c78baa3" />

The cluster proxy setup does already work for us when using the same root domain. This issue is about using different root domains. The CORS error only appears when using different root domains

**Comment by gustavotrott** [comment]
I apologize! I actually ran into a similar issue even when using the same root domain, so I initially thought you might be facing the same problem I had.

But looking at it more closely now, it’s true that this issue does happen when the root domains are different.

I managed to work around it by setting:

```
sudo yq eval '.server.servlet.session.cookie.SameSite = "none"' -i /usr/share/bbb-web/WEB-INF/classes/application.yml
sudo systemctl restart bbb-web
```

(I also included that nginx config I commented above)

I tested using two completely different domains:

https://github.com/user-attachments/assets/46717d46-0fcf-460d-899b-acf3489bfef6

**Comment by michelleDeko** [comment]
Hi @gustavotrott, thanks, it seems to work with this:
```
sudo yq eval '.server.servlet.session.cookie.SameSite = "none"' -i /usr/share/bbb-web/WEB-INF/classes/application.yml
sudo systemctl restart bbb-web
```

I also tried doing it without the nginx config changes and it still works, so the nginx config changes are not needed.

This should probably get added to the documentation

**Comment by gustavotrott** [comment]
> Hi [@gustavotrott](https://github.com/gustavotrott), thanks, it seems to work with this:
> 
> ```
> sudo yq eval '.server.servlet.session.cookie.SameSite = "none"' -i /usr/share/bbb-web/WEB-INF/classes/application.yml
> sudo systemctl restart bbb-web
> ```
> 
> I also tried doing it without the nginx config changes and it still works, so the nginx config changes are not needed.
> 
> This should probably get added to the documentation

Thanks for the feedback.
Yes, I'll update Docs with this setting.

**Comment by gustavotrott** [comment]
Hi @michelleDeko, could you confirm if you have set `allowRequestsWithoutSession=true` in the `/etc/bigbluebutton/bbb-web.properties` on your BBB server?

I'm trying to understand why I needed to add the nginx rule, but you didn't.

**Comment by michelleDeko** [comment]
@gustavotrott no I didn't set `allowRequestsWithoutSession`

I only did 
```
sudo yq eval '.server.servlet.session.cookie.SameSite = "none"' -i /usr/share/bbb-web/WEB-INF/classes/application.yml
sudo systemctl restart bbb-web
```
