### ISSUE TITLE
Wrong path in `disable-transparent-huge-pages.service`

### ISSUE THREAD

**Issue by paulmenzel** [bigbluebutton/bigbluebutton#9077]
*bbb-html5* 1:2.2.0-874 contains the systemd service unit `disable-transparent-huge-pages.service` fails to start.

```
$ systemctl cat disable-transparent-huge-pages.service 
# /usr/lib/systemd/system/disable-transparent-huge-pages.service
[Unit]
Description=Disable Transparent Huge Pages

[Service]
Type=oneshot
ExecStart=/bin/sh -c "/usr/bin/echo "never" | tee /sys/kernel/mm/transparent_hugepage/enabled"
ExecStart=/bin/sh -c "/usr/bin/echo "never" | tee /sys/kernel/mm/transparent_hugepage/defrag"

[Install]
WantedBy=multi-user.target
```

`/usr/bin/sh` does not exist in Ubuntu 16.04.

    $ ls /usr/bin/sh
    ls: cannot access '/usr/bin/sh': No such file or directory

Changing the lines to `/bin/sh` the service can be started.

PS: I couldn’t find the source for the service unit in the BigBlueButton GitHub project.

**Comment by basisbit** [comment]
fyi @ffdixon

**Comment by ffdixon** [comment]
Done -- the fix will be in upcoming 2.2.6.   Thanks for pointing this out.

Reference: https://docs.mongodb.com/manual/tutorial/transparent-huge-pages/

**Comment by paulmenzel** [comment]
This regressed again when updating *bbb-html5* to 1:2.2.0-908. Can you backport that for older versions?

**Comment by hex-m** [comment]
Can confirm this problem occurs on 2.2.10.

**Comment by ffdixon** [comment]
@hex-m thanks for reporting this -- will be fixed in 2.2.11.

**Comment by hex-m** [comment]
tested on 2.2.11: the service does not fail anymore, but looking at the logs there is still a problem:

```
# journalctl -u disable-transparent-huge-pages
May 16 23:57:33 bbb1 systemd[1]: Starting Disable Transparent Huge Pages...
May 16 23:57:33 bbb1 sh[26484]: /bin/sh: 1: /usr/bin/echo: not found
May 16 23:57:33 bbb1 sh[26490]: /bin/sh: 1: /usr/bin/echo: not found
May 16 23:57:33 bbb1 systemd[1]: Started Disable Transparent Huge Pages.
```
So the path for `sh` is correct now, but the path to `echo` is wrong.
```
# cat /usr/lib/systemd/system/disable-transparent-huge-pages.service 
[Unit]
Description=Disable Transparent Huge Pages

[Service]
Type=oneshot
ExecStart=/bin/sh -c "/usr/bin/echo "never" | tee /sys/kernel/mm/transparent_hugepage/enabled"
ExecStart=/bin/sh -c "/usr/bin/echo "never" | tee /sys/kernel/mm/transparent_hugepage/defrag"

[Install]
WantedBy=multi-user.target
```

**Comment by ffdixon** [comment]
Good catch -- will fix in 2.2.12.

**Comment by odenbach** [comment]
May I suggest another aproach:

- add a dependancy to `sysfsutils` to the bbb-package which needs the setting
- add a file `/etc/sysfs.d/bbb-xxx.conf` containing the needed settings:

`kernel/mm/transparent_hugepage/enabled = 1
`

and you are done with it. This seems to be the correct and natural way of setting sysfs variables at boot time.

Thanks,

Christopher

**Comment by GhaziTriki** [comment]
@odenbach do you confirm that you tested the suggested approach?

**Comment by odenbach** [comment]
@GhaziTriki We have been doing this for years now, so I am sure it works.

Just to make sure I just tried it on my test BBB machine. I disabled the disable-transparent-huge-pages.service (masked it as well) and rebooted to have a look at the default settings: Both kernel settings showed "never". Then I had a closer look:

bbb-html5.service starts a script /usr/share/meteor/bundle/systemd_start.sh which also sets the sysfs parameters.

So currently I think the setting is done twice which makes one of them redundant. Still I think that the syfsutils approach is much cleaner and better to maintain.

Regards,

Christopher

**Comment by dahrens** [comment]
In version `2.3.1` it is not included in `/usr/share/meteor/bundle/systemd_start.sh` anymore.

**Comment by paulmenzel** [comment]
@dahrens, can you please elaborate? What was included in `/usr/share/meteor/bundle/systemd_start.sh` before 2.3.1?

**Comment by dahrens** [comment]
I don't know. I just read the hint of @odenbach that the disabling of `transparent-huge-pages` was made there as well (in prior version) and checked if this is still the case, but it isn't. The oldest version available to me is 2.2.0 - in this version `/usr/share/meteor/bundle/systemd_start.sh` does not disable  `transparent-huge-pages`.
